name: Build and Deploy
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven

    - name: Running Tests
      run: mvn -B clean

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.13
      with:
        heroku_api_key: ae99a02d-a9b1-44df-b5cb-94cda0925393
        heroku_app_name: nuzones
        heroku_email: uobjuniorsolutions@gmail.com
