name: Build and Deploy
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
      
    - name: Rename the artifact
      run: cp target/nuzones-service-0.0.1-SNAPSHOT.jar target/nuzones-service-${{ github.sha }}.jar

    - name: install ssh-agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: target/nuzones-service-${{ github.sha }}.jar
        target: app/nuzones/nuzones-service-${{ github.sha }}.jar